spring:
  application:
    name: restful-service

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      pool-name: H2Pool

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

# Secondary (MySQL) datasource configuration
mysql:
  datasource:
    url: jdbc:mysql://localhost:3306/collegedb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    hikari:
      pool-name: MySQLPool
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
